### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZHENGLOC** [62832/MEGACells#62] opened 2023-07-23 04:06 UTC
When I put the MEGA Bulk Item Storage Cell in the ME Drive after marking the items and installing the Compression Card in Cell Workbench, there is a high probability that it will crash.
I have the MEGA Decompression Module installed in my AE network.
The items I mark are: Redstone, Flint, Iron Ingot, Copper Ingot, Zinc Ingot (Create), Glowstone Dust, Nether Quartz, Gold Ingot. All have Compression Card installed.
(Machine Translation)

Forge version: 43.2.21
Mod version: megacells-forge-2.0.0-1.19.2
Game version:1.19.2

Crash report and log:
[latest.log](https://github.com/62832/MEGACells/files/12137976/latest.log)
[crash-2023-07-23_11.43.01-server.txt](https://github.com/62832/MEGACells/files/12137977/crash-2023-07-23_11.43.01-server.txt)

**Comment by ZHENGLOC** [comment] 2023-07-23 04:29
Now I can't even get into single player
[crash-2023-07-23_12.26.49-server.txt](https://github.com/62832/MEGACells/files/12138012/crash-2023-07-23_12.26.49-server.txt)

**Comment by 62832** [comment] 2023-07-23 07:41
Do you have any specific steps to reproduce either of the two on a new world?

**Comment by ZHENGLOC** [comment] 2023-07-23 12:39
> Decompression Module

I reproduced the crash.
I used a small modpack to reproduce it, here is the list of mods:

almostunified-forge-1.19.2-0.5.0
appliedenergistics2-forge-12.9.5
create-1.19.2-0.5.1.c
 jei-1.19.2-forge-11.6.0.1016
megacells-forge-2.0.0-1.19.2
moonlight-1.19.2-2.2.43-forge
supplementaries-1.19.2-2.3.20
notenoughcrashes-4.2.1+1.19.2-forge

My English is not very good, so I recorded a video.

https://github.com/62832/MEGACells/assets/24859848/c7483a5a-9345-41b8-95ac-6b5bf556251f

**Comment by ZHENGLOC** [comment] 2023-07-23 12:40
> Do you have any specific steps to reproduce either of the two crashes on a new world?


I reproduced the crash.
I used a small modpack to reproduce it, here is the list of mods:

almostunified-forge-1.19.2-0.5.0
appliedenergistics2-forge-12.9.5
create-1.19.2-0.5.1.c
 jei-1.19.2-forge-11.6.0.1016
megacells-forge-2.0.0-1.19.2
moonlight-1.19.2-2.2.43-forge
supplementaries-1.19.2-2.3.20
notenoughcrashes-4.2.1+1.19.2-forge

My English is not very good, so I recorded a video.

https://github.com/62832/MEGACells/assets/24859848/c7483a5a-9345-41b8-95ac-6b5bf556251f

**Comment by 62832** [comment] 2023-07-23 18:55
I'm unable to reproduce this in single player with the setup you've provided. Is the mod list you've given the same on the server side rather than just the client?

**Comment by ZHENGLOC** [comment] 2023-07-23 19:21
> I'm unable to reproduce this in single player with the setup you've provided. Is the mod list you've given the same on the server side rather than just the client?

I'm not running it on a server, it's single player.
I reduced the number of mods in the test modpack and only kept:

appliedenergistics2-forge-12.9.5
 jei-1.19.2-forge-11.6.0.1016
megacells-forge-2.0.0-1.19.2

I'm using hopper to feed items into the ME interface this time. Also crashes.

[latest.log](https://github.com/62832/MEGACells/files/12139789/latest.log)
[crash-2023-07-24_03.14.06-server.txt](https://github.com/62832/MEGACells/files/12139794/crash-2023-07-24_03.14.06-server.txt)

**Comment by 62832** [comment] 2023-07-23 19:29
I have been able to reproduce this now when running a locally-hosted server. I think I may have a fix for this coming up in a bit.

**Comment by 62832** [comment] 2023-07-23 19:43
Version 2.0.1 will be releasing in the next 15 or so minutes, and should hopefully have fixed this crash.

**Closed by 62832** 2023-07-23 19:43 UTC
