### ISSUE TITLE
MEGA Bulk Item Storage doesn't work for autocrafting

### ISSUE THREAD

**Issue by ManciDRaffy** [62832/MEGACells#83] opened 2023-10-27 12:03 UTC
I put in Iron Nuggets and enabled compression. Sadly now the crafting recipes doesn't work anymore.
It shows everything is available, but it still says "Crafting Ingredients Missing".

Any kind of item doesn not work for crafting after it got put into a BULK Item Storage

Modpack: ATM: VB

**Comment by 62832** [comment] 2023-10-27 17:38
Duplicate of #81?

**Closed by 62832** 2023-10-27 17:38 UTC
