### ISSUE TITLE
Feature idea: ME DISK Drives up to 256M when AE2 Things is installed

### ISSUE THREAD

**Issue by James103** [62832/MEGACells#31] opened 2022-12-11 03:49 UTC
Currently, when both MEGA Cells and [AE2 Things](https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge) are installed, AE2 Things provides ME DISK Drives which can store up to between 1,000 and 256,000 items, whatever that's 256,000 stone or 256,000 different enchanted books, gear items, Apotheosis gems, or other unique items.

However, MEGA Cells adds bigger cells that can store items, fluids, and chemicals, why not bigger ME DISK Drives (up to 256M)?

Furthermore, Refined Storage + Extra Disks has equivalent disk drives up to 256M items, along with a billion-item storage disk and a storage disk with no item or type limits. Neither are required for this integration, but they would be nice.

**Comment by 62832** [comment] 2022-12-11 11:23
Duplicate of #3. If the demand gets high enough I may reconsider, but for now I still don't think I'd like to.

**Closed by 62832** 2022-12-11 11:23 UTC
