### ISSUE TITLE
Latest Update causes Server Watchdog Crash on Startup

### ISSUE THREAD

**Issue by LokeYourC3PH** [62832/MEGACells#70] opened 2023-08-29 12:45 UTC
What the title says. The latest update causes the server to hang on startup with the following crashlog:
[crash-2023-08-29_13.40.25-server.txt](https://github.com/62832/MEGACells/files/12464621/crash-2023-08-29_13.40.25-server.txt)

**Comment by 62832** [comment] 2023-08-29 13:36
That's very concerning. I'll have to investigate.

**Comment by Alexander-Jennings** [comment] 2023-08-29 13:37
I have an infinit loading scrren when loading a world.

**Comment by Alexander-Jennings** [comment] 2023-08-29 13:40
I have only tested it on Fabric.

**Comment by 62832** [comment] 2023-08-29 13:42
I'm unable to reproduce this so far in either development or production. Are you playing a larger pack?

**Comment by Alexander-Jennings** [comment] 2023-08-29 13:44
Yes, I am going to start testing the mods individually.

**Comment by Alexander-Jennings** [comment] 2023-08-29 13:44
Yes, I am going to start testing the mods individually.

**Comment by 62832** [comment] 2023-08-29 14:01
Turns out I've made a glaring mistake with the compression service that's making it do more than double the work for each individual chain of compressible items. I'll be adapting this and releasing a fix as soon as possible.

**Comment by Alexander-Jennings** [comment] 2023-08-29 14:20
Ithink i got it.
This combination of mods breaks it.

```
16:17:12.974
net.minecraft.class_163
Render thread
Loaded 3770 advancements
16:17:14.532
net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl
Render thread
Applied 129 biome modifications to 65 of 65 new biomes in 29.10 ms
16:17:14.665
AE2:S
Server thread
Scanning class appeng.server.testplots.TestPlots for plots
16:17:14.670
AE2:S
Server thread
Scanning class appeng.server.testplots.AutoCraftingTestPlots for plots
16:17:14.671
AE2:S
Server thread
Scanning class appeng.server.testplots.P2PTestPlots for plots
16:17:14.671
AE2:S
Server thread
Scanning class appeng.server.testplots.MemoryCardTestPlots for plots
16:17:14.672
AE2:S
Server thread
Scanning class appeng.server.testplots.PatternProviderLockModePlots for plots
16:17:14.672
AE2:S
Server thread
Scanning class appeng.server.testplots.SpatialTestPlots for plots
16:17:14.672
AE2:S
Server thread
Scanning class appeng.server.testplots.QnbTestPlots for plots
16:17:14.673
AE2:S
Server thread
Scanning class appeng.server.testplots.GuidebookPlot for plots
16:17:14.673
AE2:S
Server thread
Scanning class appeng.server.testplots.SubnetPlots for plots
16:17:14.679
net.minecraft.class_1132
Server thread
Starting integrated minecraft server version 1.20.1
16:17:14.679
net.minecraft.server.MinecraftServer
Server thread
Generating keypair
16:17:18.253
net.minecraft.server.MinecraftServer
Server thread
Preparing start region for dimension minecraft:overworld
16:17:21.699
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:21.750
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:21.754
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:21.754
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:21.755
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:21.755
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:21.804
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:21.804
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:22.265
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:22.781
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:23.272
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:23.757
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
16:17:24.280
net.minecraft.class_3951
Render thread
Preparing spawn area: 3%
16:17:24.760
net.minecraft.class_3951
Render thread
Preparing spawn area: 45%
16:17:25.758
net.minecraft.class_3951
Render thread
Time elapsed: 7503 ms
16:17:55.561
launcher
main

16:17:55.562
monitor
Process Monitor
Process crashed with exit code 1
```

**Comment by Alexander-Jennings** [comment] 2023-08-29 14:23
Also I got this error in the log.
```
16:17:12.588
net.minecraft.class_1863
Render thread
Parsing error loading recipe megacells:cells/mega_mana_cell_housing
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'botania:terra_plate'
	at net.minecraft.class_1863.method_17875(class_1863.java:134)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_1863.method_17720(class_1863.java:134)
	at net.minecraft.class_1863.method_20705(class_1863.java:56)
	at net.minecraft.class_1863.method_18788(class_1863.java:35)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.class_7196.method_45694(class_7196.java:188)
	at net.minecraft.class_7196.method_41891(class_7196.java:123)
	at net.minecraft.class_7196.method_41899(class_7196.java:202)
	at net.minecraft.class_7196.method_41894(class_7196.java:64)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402)
	at net.minecraft.class_350.method_25402(class_350.java:327)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by 62832** [comment] 2023-08-29 14:23
Yeah, don't worry, this is an issue entirely independent on any specific mods. I'm currently testing an adaptation made to the overall compression service to make sure it doesn't continue to bring servers to their knees.

**Comment by 62832** [comment] 2023-08-29 14:25
> Also I got this error in the log.

This one is simply because Applied Botanics isn't present in the pack (since, of course, it isn't available yet for 1.20) and means the recipe for the mana cell housing cannot be used. It shouldn't cause any actual problems in-game.

**Comment by Alexander-Jennings** [comment] 2023-08-29 14:25
Ok. Thanks for all the work you have done. I enjoy playing with your mod.

**Comment by LokeYourC3PH** [comment] 2023-08-29 14:29
> Yeah, don't worry, this is an issue entirely independent from any specific mods. I'm currently testing an adaptation made to the overall compression service to make sure it doesn't continue to bring servers to their knees.

That was a quick investigation and fix, thanks a lot :)

**Comment by 62832** [comment] 2023-08-29 16:16
As it turns out, the approach taken of having an ever-increasing multiplier was a complete disaster due to the increased memory requirement and horrendous performance of using longs over ints. Instead, the old multipliers have been brought back, but with an added "1" multiplier for base items like nuggets.

**Comment by LokeYourC3PH** [comment] 2023-08-30 05:01
Reopen the issue, it still persists. However, now it happens after the server has fully started:
[crash-2023-08-30_05.59.53-server.txt](https://github.com/62832/MEGACells/files/12471851/crash-2023-08-30_05.59.53-server.txt)

**Comment by 62832** [comment] 2023-08-30 09:06
I had neglected to reopen after first being informed that the issue is still persisting. I've already been working on a second iteration of the compression service in the hopes of fixing it for good.

**Comment by 62832** [comment] 2023-08-30 10:59
I've pushed one more build due to release in the next 15 minutes or so. If I receive confirmation that the OOM bug is no longer present, only then will I close this issue again. Please let me know how it goes.

**Comment by LokeYourC3PH** [comment] 2023-08-30 11:39
Issue is fixed. But at what cost... I lost all, and I mean ALL MEGA Storage cells, etc. on my server after the update. They're all gone, for all players. Entire, massive world miners which stored in them, just gone. I regret updating now....

**Comment by 62832** [comment] 2023-08-30 12:02
Just for reference's sake, what pack are you currently playing on Fabric? My tests so far have been on the All The Mods 9 pack on Forge and the server proceeded just fine.

**Comment by LokeYourC3PH** [comment] 2023-08-30 12:07
> Just for reference's sake, what pack are you currently playing on Fabric? My tests so far have been on the All The Mods 9 pack on Forge and the server proceeded just fine.

Personal made pack for me and my friends :)

**Comment by LokeYourC3PH** [comment] 2023-08-30 12:16
I'll do you a better one, you can just import the pack yourself via a modpack export I made on ATLauncher. Here you go:
https://mega.nz/file/0lFGSSya#8EMOw8SRLDGff0jxcfVTjlbpO2EMbAOZKPXO9c-85F8

**Comment by 62832** [comment] 2023-08-30 12:24
I seem to be unable to actually run this pack due to a JVM segfault.

In any case, since I don't think the compression rewrite has worked out for now, I'll have to revert it all and re-evaluate how to proceed with it at all.

**Comment by 62832** [comment] 2023-08-30 12:28
On second thought, do you think I could reach out to you somewhere like Discord to test further? I have one or two remaining solutions for the time being that would require me to send development builds without a proper release.

**Comment by LokeYourC3PH** [comment] 2023-08-30 12:30
> I seem to be unable to actually run this pack due to a JVM segfault.
> 
> In any case, since I don't think the compression rewrite has worked out for now, I'll have to revert it all and re-evaluate how to proceed with it in the end.

Damn that's interesting, works just fine for me and my friends. I could help you to get it running if you want.



> On second thought, do you think I could reach out to you somewhere like Discord to test further? I have one or two remaining solutions for the time being that would require me to send development builds without a proper release.

Yea sure I do, you can reach me on Discord under (I hate the new handles, fuck Discord for that change 🤡): @lokeyourc3ph

**Comment by 62832** [comment] 2023-09-03 12:01
Since I have now both re-implemented compression overrides and managed to have two of the people previously reporting server crashes write back to me to say the problem is no longer present with the re-implementation, I will now be closing this issue for good.

**Closed by 62832** 2023-09-03 12:01 UTC
