### ISSUE TITLE
[1.21.1Neoforge]When installed with xaero's world map,MEGA crafting storage's texture will be lost

### ISSUE THREAD

**Issue by ht030515** [62832/MEGACells#147] opened 2024-10-24 09:43 UTC
![2024-10-24_17 41 41](https://github.com/user-attachments/assets/39a51808-4f3c-40f6-bf5e-4f9e7a6ddfdc)

**Comment by 62832** [comment] 2024-10-24 13:39
Duplicate of #117. Still haven't got a single clue why this might be the case, please forward this to the dev of Xaero's Minimap.

**Closed by 62832** 2024-10-24 13:39 UTC
