### ISSUE TITLE
Idea: ME MEGA FE Storage Cells

### ISSUE THREAD

**Issue by James103** [62832/MEGACells#110] opened 2024-02-21 20:21 UTC
The mod "Applied Flux" implements the feature proposed in #75, but, according to the description, only goes up to 256k FE Storage Cell, which can store approximately 1.100 × 10<sup>12</sup> FE.

However, 1.100 × 10<sup>12</sup> FE may not be enough for late-game Mekanism and some other end-game applications in mod packs. For example, Mekanism antimatter production costs 4 × 10<sup>8</sup> FE/t at the optimal production rate, while GregTech for modern versions can easily use 10<sup>9</sup> FE/t for a large end-game base. In All the Mods 9, a single Star Forge running the most expensive recipe producing Allthemodium and Unobtainium consumes 36A UHV, equivalent to almost 3 × 10<sup>8</sup> FE/t.

At these rates, 1.100 × 10<sup>12</sup> FE is only enough for 1-3 minutes of power, insufficient for long-term storage and may not give enough time to shut processes down and conserve power while the reactor or other power generation is restored.

From this, large bases wanting to use AE2 for power storage and distribution will need higher capacity cells. This can be implemented by extending the FE storage cells implemented in Applied Flux with 1M through 256M variants, allowing for a maximum FE capacity of 1.126 × 10<sup>15</sup> FE in a single cell, equivalent to about 15 hours of power at 10<sup>9</sup> FE/t. If more power is desired, additional FE cells can always be added to the drive; a drive full of them can hold 1.126 × 10<sup>16</sup> FE, or about 150 hours, and 8 such drives can hold 9.007 × 10<sup>16</sup> FE, or about 1200 hours.

**Comment by 62832** [comment] 2024-02-21 21:35
Duplicate of #109, but you make some pretty good points which would be worth throwing in that issue.

**Closed by 62832** 2024-02-21 21:35 UTC
